# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: GUI-SDL2
description: GUI-SDL2 is SDL2, SDL2_image and SDL2_ttf based desktop GUI that is completely written in Haskell.
synopsis: GUI-SDL2 is SDL2, SDL2_image and SDL2_ttf based desktop GUI that is completely written in Haskell.
category: GUI SDL2
license: BSD3
maintainer: Kolodezny Diver
github: KolodeznyDiver/GUI-SDL2
version: '0.1.8'
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
- GUI.Resources/**

flags:
  examples:
    description: Build examples
    default:     False
    manual:      True

executables:
  GUIDemo:
    main: Main.hs
    source-dirs: examples
    when:
      - condition: flag(examples)
        then:
          dependencies:
          - base
          - GUI-SDL2
          - bytestring
          - safe-exceptions
          - linear
          - text
          - transformers
          - vector
          - sdl2
          - sdl2-ttf
          - sdl2-image
          - stm
          - ghc
          - data-default
          - text-show
          ghc-options:
          - -Wall
          - -Wname-shadowing
          - -fwarn-tabs
          - -rtsopts
          - -threaded
          - -with-rtsopts=-N
        else:
          buildable: False

library:
  exposed-modules:
  - GUI.BaseLayer.Depend0.Auxiliaries
  - GUI.BaseLayer.Depend0.BitFlags
  - GUI.BaseLayer.Depend0.Cursor
  - GUI.BaseLayer.Depend0.Keyboard
  - GUI.BaseLayer.Depend0.Pipe
  - GUI.BaseLayer.Depend0.Ref
  - GUI.BaseLayer.Depend0.TTF
  - GUI.BaseLayer.Depend0.Types
  - GUI.BaseLayer.Depend1.Action
  - GUI.BaseLayer.Depend1.Color
  - GUI.BaseLayer.Depend1.Geometry
  - GUI.BaseLayer.Depend1.Logging
  - GUI.BaseLayer.Depend1.Resource
  - GUI.BaseLayer.Depend1.Skin
  - GUI.BaseLayer.Action
  - GUI.BaseLayer.Canvas
  - GUI.BaseLayer.Canvas.Types
  - GUI.BaseLayer.Focus
  - GUI.BaseLayer.GUIRecord
  - GUI.BaseLayer.NaturalLangIO
  - GUI.BaseLayer.RunGUI
  - GUI.BaseLayer.Pipe
  - GUI.BaseLayer.PopupWindow
  - GUI.BaseLayer.Primitives
  - GUI.BaseLayer.Resource
  - GUI.BaseLayer.Types
  - GUI.BaseLayer.RedrawWindow
  - GUI.BaseLayer.UniqueCode
  - GUI.BaseLayer.Core
  - GUI.BaseLayer.Widget
  - GUI.BaseLayer.Window
  - GUI.Skin.DefaultSkin
  - GUI.Utils.TextWrap
  - GUI.Utils.Wrap
  - GUI.Widget.Container.Border
  - GUI.Widget.Container.ScrollArea
  - GUI.Widget.Internal.LinearTrackBar
  - GUI.Widget.Layout.TH.LinearLayout
  - GUI.Widget.Layout.LinearLayout
  - GUI.Widget.Layout.LinearLayoutUtils
  - GUI.Widget.TH.LinearTrackBar
  - GUI.Widget.Button
  - GUI.Widget.Handlers
  - GUI.Widget.Menu.Horizontal
  - GUI.Widget.Label
  - GUI.Widget.LinearTrackBar
  - GUI.Widget.Splitter
  - GUI.Widget.TextEdit
  - GUI.Widget.TH
  - GUI.Widget.Types
  - GUI.Window.MessageBox
  - GUI.Window.PopupMenu
  - GUI
  - Data.Vector.Utils
  - System.Utils
  when:
    - condition: os(windows)
      then:
        other-modules:
        - System.Win32.Utils
      else:
        other-modules:
        - System.X11.Utils
  extra-libraries:
  - SDL2
  - SDL2_ttf
  - SDL2_image
  dependencies:
  - base
  - template-haskell
  - ghc
  - bytestring
#  - exceptions
  - safe-exceptions
  - linear
  - StateVar
  - text
  - transformers
  - vector
  - containers
  - unordered-containers
  - data-default
  - time
  - text-show
  - filepath
  - directory
  - monadplus
  - sdl2
  - sdl2-ttf
  - sdl2-image
  when:
    - condition: os(windows)
      then:
        dependencies: Win32
      else:
        dependencies: setlocale
  ghc-options:
  - -Wall
  - -Wname-shadowing
  - -fwarn-tabs
  source-dirs: library
